name = "lifeos"
compatibility_date = "2026-07-18"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "lifeos-prod"
database_id = "a79f7649-050d-49ad-af02-853ed6deec0e"
preview_database_id = "a79f7649-050d-49ad-af02-853ed6deec0e"
